-- 관객 심사위원 "통합 계정" — 사람(audience_judges)과 대회 참여(online_judges)를 분리한다.
--
-- 배경:
--   0026 의 online_judges 는 대회 단위 행이라 "사람" 개념이 없었다. 그래서 같은 사람이
--   Bachata AMATURE 에 등록해도 Kizomba OPEN 에서는 남남 — 사진·이름·PIN 을 다시 입력해야 했다.
--
-- 이후 구조:
--   audience_judges = 사람(계정). 이메일 1개 = 계정 1개. 전역 심사위원 번호(judge_no) 보유.
--   online_judges   = "이 사람이 이 대회에 참여" 기록. 컬럼/집계 로직은 그대로 —
--                     결승 채점(online_judge_votes)이 online_judges.id 를 키로 쓰기 때문에
--                     기존 코드를 건드리지 않으려면 이 행은 반드시 유지해야 한다.
--
-- 등록 정책(앱):
--   한 번 등록하면 같은 group_name(같은 페스티벌) 의 열린 대회 전체에 즉시 참여 행이 생긴다.
--
-- 개인정보(이메일/연락처/PIN)를 담으므로 online_judges 와 같이 anon 정책 없음 — service_role 전용.

create table if not exists public.audience_judges (
  id uuid primary key default gen_random_uuid(),
  -- 전역 심사위원 번호. 대회별 display_order(1..~1000) 와 섞이지 않도록 100001 부터 시작한다.
  --   로그인 입력값이 6자리면 전역 번호, 3자리 이하면 옛 대회별 번호로 구분할 수 있다.
  judge_no bigint generated by default as identity (start with 100001) not null unique,
  -- 이름 — online_judges 와 동일 규칙(first/last 분리, name 은 표시명=last 우선).
  first_name text not null default '',
  last_name text not null default '',
  name text not null default '',
  -- 국가.
  representative text not null default '',
  email text not null default '',
  -- 이메일 비교용 정규화(생성 컬럼). ilike 로 찾으면 주소 안의 '_' 가 와일드카드로 먹히므로
  --   조회는 반드시 이 컬럼에 = 로 한다.
  email_key text generated always as (lower(btrim(coalesce(email, '')))) stored,
  phone text not null default '',
  -- 연락처 비교용 숫자만 — 앱의 중복 검사와 계정 찾기에 쓴다.
  --   유니크로 걸지 않는다: 가족/커플이 번호를 공유하는 경우가 있고,
  --   유니크면 아래 백필이 이메일 기준 그룹과 충돌해 계정이 누락된다.
  phone_key text generated always as (regexp_replace(coalesce(phone, ''), '[^0-9]', '', 'g')) stored,
  photo_url text not null default '',
  -- 4자리 숫자 PIN. 계정 단위 — 어느 대회에서 로그인하든 같은 PIN.
  pin text not null default '' check (pin = '' or pin ~ '^[0-9]{4}$'),
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 이메일 1개 = 계정 1개. 대소문자/공백 무시.
create unique index if not exists audience_judges_email_key
  on public.audience_judges (email_key)
  where email_key <> '';

create index if not exists audience_judges_phone_idx
  on public.audience_judges (phone_key)
  where phone_key <> '';

drop trigger if exists trg_audience_judges_touch on public.audience_judges;
create trigger trg_audience_judges_touch before update on public.audience_judges
  for each row execute function public.touch_updated_at();

alter table public.audience_judges enable row level security;

-- online_judges → 계정 연결. 계정을 지우면 참여 기록(과 그 채점)도 함께 사라진다.
alter table public.online_judges
  add column if not exists audience_judge_id uuid references public.audience_judges(id) on delete cascade;

-- 한 사람이 같은 대회에 두 번 참여할 수 없다(일괄 등록 재실행 시 중복 방지).
create unique index if not exists online_judges_contest_account_key
  on public.online_judges (contest_id, audience_judge_id)
  where audience_judge_id is not null;

create index if not exists online_judges_account_idx
  on public.online_judges (audience_judge_id)
  where audience_judge_id is not null;

-- ── 백필 ────────────────────────────────────────────────────────────────────
-- 기존 등록을 이메일(소문자) 기준으로 묶어 계정을 만든다.
-- 같은 이메일인데 대회마다 프로필/PIN 이 다르면 가장 최근에 갱신된 행을 채택한다.
insert into public.audience_judges (first_name, last_name, name, representative, email, phone, photo_url, pin, created_at)
select distinct on (lower(btrim(oj.email)))
  oj.first_name, oj.last_name, oj.name, oj.representative,
  btrim(oj.email), oj.phone, oj.photo_url, oj.pin, oj.created_at
from public.online_judges oj
where btrim(coalesce(oj.email, '')) <> ''
order by lower(btrim(oj.email)), oj.updated_at desc, oj.created_at desc
on conflict do nothing;

update public.online_judges oj
set audience_judge_id = aj.id
from public.audience_judges aj
where oj.audience_judge_id is null
  and btrim(coalesce(oj.email, '')) <> ''
  and lower(btrim(oj.email)) = aj.email_key;

-- 이메일이 비어있던 옛 행은 계정 없이 남는다(audience_judge_id is null).
--   → 로그인 폴백 경로(대회별 등록 번호 + PIN)로 계속 접속할 수 있다.

-- ── 기존 등록자 일괄 참여 ────────────────────────────────────────────────────
-- 새 정책(한 번 등록 = 같은 페스티벌 전체 참여)을 이미 등록한 사람들에게도 소급 적용한다.
-- 이걸 빼면 "Bachata 에 등록했는데 Kizomba 에서 또 등록하라고 한다" 는 원래 문제가
-- 기존 등록자에게만 그대로 남는다.
--   대상: 같은 group_name 안에서 한 대회라도 참여 중인 계정 × 그 그룹의 열린 대회.
--   group_name 이 빈 대회(미분류)는 서로 남남이므로 제외.
with account_groups as (
  select distinct oj.audience_judge_id as account_id, c.group_name
  from public.online_judges oj
  join public.contests c on c.id = oj.contest_id
  where oj.audience_judge_id is not null
    and btrim(coalesce(c.group_name, '')) <> ''
),
targets as (
  select ag.account_id, c.id as contest_id
  from account_groups ag
  join public.contests c
    on c.group_name = ag.group_name
   and c.status not in ('archived', 'done')
   and coalesce(c.audience_listed, true)
  where not exists (
    select 1 from public.online_judges oj
    where oj.contest_id = c.id and oj.audience_judge_id = ag.account_id
  )
),
numbered as (
  select
    t.account_id,
    t.contest_id,
    coalesce(
      (select max(oj.display_order) from public.online_judges oj where oj.contest_id = t.contest_id),
      0
    ) + row_number() over (partition by t.contest_id order by t.account_id) as display_order
  from targets t
)
insert into public.online_judges
  (contest_id, display_order, audience_judge_id, first_name, last_name, name,
   representative, email, phone, photo_url, pin)
select
  n.contest_id, n.display_order, aj.id, aj.first_name, aj.last_name, aj.name,
  aj.representative, aj.email, aj.phone, aj.photo_url, aj.pin
from numbered n
join public.audience_judges aj on aj.id = n.account_id
on conflict do nothing;
